import {
    themeDarkNotificationError,
    themeDarkNotificationWarningSoft,
    themeLightBackgroundBase,
    themeLightContrastHigh,
    themeLightNotificationErrorSoft,
    themeLightNotificationInfo,
    themeLightNotificationSuccess,
    themeLightNotificationWarning,
    themeLightNotificationWarningSoft,
    themeLightPrimary,
    themeLightStateDisabled,
    themeDarkBackgroundShading,
    themeLightBackgroundShading,
} from "@porsche-design-system/components-react/styles";

const colors = {
    porscheBlack: themeLightPrimary,
    porscheBlackShaded: themeLightBackgroundShading,
    allWhite: themeLightBackgroundBase,
    whiteOpaque: "rgba(255, 255, 255, 0.08)",
    white20: "rgba(255, 255, 255, 0.2)",
    white10: "rgba(255, 255, 255, 0.1)",
    blackOpaque: "rgba(0, 0, 0, 0.05)",
    motorsportsRed: "#E00000",
    backgroundRed: "#CA3230",
    grey700: "#6b6d70",
    grey600: "#808082",
    grey500: themeLightContrastHigh,
    grey400: themeLightStateDisabled,
    grey300: "#595959",
    grey200: "#CCCCCC",
    grey100: "#EEEFF2",
    grey50: "#F7F7F7",
    backgroundShading: themeDarkBackgroundShading,
    notificationError: themeDarkNotificationError,
    notificationErrorSoft: themeLightNotificationErrorSoft,
    notificationWarning: themeLightNotificationWarning,
    notificationWarningSoft: themeDarkNotificationWarningSoft,
    notificationSuccess: themeLightNotificationSuccess,
    notificationSuccessSoft: themeLightNotificationWarningSoft,
    notificationInfo: themeLightNotificationInfo,
    notificationInfoSoft: themeLightNotificationWarningSoft,
    transparent: "rgba(0, 0, 0, 0)",
    formulaE: "#4e288b",
    liveTimingIndicatorYellow: "#FFDE21",
    liveTimingIndicatorPurple: "#DC3AE8",
    liveTimingIndicatorGreen: "#08AB08",
    liveTimingIndicatorRed: "#E31E3E",
    liveTimingClassRookie: "rgb(242,161,0)",
    liveTimingClassProAm: "rgb(58,107,155)",
    liveTimingClassMasters: "rgb(205,127,50)",
    liveTimingClassHypercar: "rgb(226, 30, 25)",
    liveTimingClassLMGT3: "rgb(0, 150, 57)",
    liveTimingClassLMP2: "rgb(53, 87, 137)",
    liveTimingClassGTDPro: "#E61D26",
    liveTimingClassGTD: "#01AB51",
    liveTimingClassGTP: "#000000",
    // New Design Language
    ndlMotorsportsRed: "#DC0527",
    ndlFormulaE: "#8A1AFF",
    ndlCaymanBlue: "#283EF1",
    ndlCoanda: "#FBFCFF",
    ndlBlack: "#000000",
    ndlGrey: "#1C1C1C",
    ndlBackgroundDarkGrey: "rgb(1, 2, 5, 0.3)",
    ndlTransparencyGrey: "rgba(95, 95, 97, 0.35)",
    ndlTransparencyGreyHover: "rgba(95, 95, 97, 0.80)",
    ndlTransparenceDarkGrey: "rgba(99, 99, 105, 0.35)",
    ndlTransparencyBlack: themeLightBackgroundShading,
    ndlTransparencyBlackHover: "rgba(26, 26, 30, 0.7)",
    // New Design Language (NDL) - Language Selector tokens
    ndlLanguageSelectorNonActiveBg: "rgba(83, 84, 87, 0.40)",
    ndlLanguageSelectorActiveBg: "rgba(204, 204, 204, 0.30)",
    ndlLanguageSelectorHoverBg: "rgba(255,255,255,0.1)",
    ndlLanguageSelectorTextColor: themeLightBackgroundBase,
    ndlLanguageSelectorPlaceholderColor: "rgba(255,255,255,0.6)",
    ndlLanguageSelectorDarkgray: "rgba(1, 2, 5, 0.30)",
    // New Design Language (NDL) - Heading gradient tokens
    ndlHeadingGradientGrey: "#CBCBCB",
    ndlHeadingGradientLight: "rgb(243, 243, 243)",
    ndlHeadingGradientDarkChannels: "57, 57, 57",
};

export default colors;
